"""Paper-aligned Satellite domain pipeline for the Coastal Erosion Prediction Platform.

Primary method reference:
Chawalit et al. (2025), "Geoinformatics and Machine Learning for Shoreline
Change Monitoring: A 35-Year Analysis of Coastal Erosion in the Upper Gulf
of Thailand", DOI 10.3390/ijgi14020094.

The live path uses public Landsat Collection 2 Level-2 imagery discovered
through the Microsoft Planetary Computer STAC API. If live acquisition or
optional geospatial dependencies are unavailable, the pipeline falls back
to deterministic synthetic data with the same output schema.

Important: when live training labels are not available locally, the
Random Forest classification is explicitly a pseudo-label fallback seeded
from MNDWI. This is an implementation adaptation, not claimed to reproduce
the paper's labelled training set exactly.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import os
import random
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import requests
from shapely.geometry import shape

ROOT = Path(__file__).resolve().parents[3]
AOI_PATH = ROOT / "config" / "aoi.geojson"
OUTPUT_DIR = ROOT / "outputs"
SATELLITE_CSV = OUTPUT_DIR / "satellite_domain_output.csv"
SATELLITE_GEOJSON = OUTPUT_DIR / "satellite_map.geojson"
SATELLITE_RUN = OUTPUT_DIR / "satellite_run.json"
SATELLITE_RAW_DIR = OUTPUT_DIR / "satellite_raw"
SATELLITE_RAW_IMG = SATELLITE_RAW_DIR / "latest_raw_rgb.png"
SATELLITE_RAW_META = SATELLITE_RAW_DIR / "latest_raw_metadata.json"

STAC_URL = "https://planetarycomputer.microsoft.com/api/stac/v1/search"
COLLECTION = "landsat-c2-l2"
MAX_CLOUD = 35.0
LIVE_LOOKBACK_DAYS = 365

PAPER = {
    "title": "Geoinformatics and Machine Learning for Shoreline Change Monitoring: A 35-Year Analysis of Coastal Erosion in the Upper Gulf of Thailand",
    "authors": "Chawalit et al.",
    "year": 2025,
    "doi": "10.3390/ijgi14020094",
}

SPECTRAL_COLUMNS = ["blue", "green", "red", "nir", "swir1", "swir2"]
INDEX_COLUMNS = ["ndvi", "ndwi", "mndwi", "savi"]


def load_aoi() -> tuple[dict[str, Any], tuple[float, float, float, float]]:
    with AOI_PATH.open("r", encoding="utf-8") as f:
        data = json.load(f)
    geom = shape(data["features"][0]["geometry"])
    return data, geom.bounds


def load_segment_points() -> list[dict[str, Any]]:
    # Prefer existing segment geometry generated by the project.
    candidate = OUTPUT_DIR / "map_data.geojson"
    if candidate.exists():
        try:
            data = json.loads(candidate.read_text(encoding="utf-8"))
            points = []
            for feature in data.get("features", []):
                coords = feature.get("geometry", {}).get("coordinates", [])
                props = feature.get("properties", {})
                if len(coords) >= 2:
                    points.append(
                        {
                            "segment_id": str(props.get("segment_id")),
                            "longitude": float(coords[0]),
                            "latitude": float(coords[1]),
                        }
                    )
            if points:
                return points
        except (OSError, ValueError, TypeError):
            pass

    # Deterministic fallback coastal sampling line within the configured AOI.
    _, (minx, miny, maxx, maxy) = load_aoi()
    n = 100
    points = []
    for i in range(n):
        t = i / (n - 1)
        lat = maxy - 0.86 * (maxy - miny) * t
        lon = (maxx - 0.03) - 0.12 * t
        points.append(
            {
                "segment_id": f"SEG_{i + 1:03d}",
                "longitude": float(lon),
                "latitude": float(lat),
            }
        )
    return points


def search_latest_landsat() -> dict[str, Any]:
    _, bbox = load_aoi()
    end = dt.datetime.now(dt.timezone.utc)
    start = end - dt.timedelta(days=LIVE_LOOKBACK_DAYS)
    payload = {
        "collections": [COLLECTION],
        "bbox": list(bbox),
        "datetime": f"{start.isoformat().replace('+00:00', 'Z')}/{end.isoformat().replace('+00:00', 'Z')}",
        "limit": 20,
        "query": {"eo:cloud_cover": {"lte": MAX_CLOUD}},
        "sortby": [{"field": "datetime", "direction": "desc"}],
    }
    response = requests.post(STAC_URL, json=payload, timeout=30)
    response.raise_for_status()
    features = response.json().get("features", [])
    if not features:
        raise RuntimeError("No Landsat Collection 2 Level-2 scene found in the live search window.")
    return features[0]


def _sign_item(item_json: dict[str, Any]):
    import pystac
    import planetary_computer

    item = pystac.Item.from_dict(item_json)
    return planetary_computer.sign(item)


def _scaled(values: np.ndarray) -> np.ndarray:
    values = values.astype("float64")
    values[values == 0] = np.nan
    return values * 0.0000275 - 0.2


def _safe_ratio(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    den = a + b
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(np.abs(den) > 1e-9, (a - b) / den, np.nan)


def _sample_from_signed_assets(signed_item, coordinates: list[tuple[float, float]]):
    import rasterio

    assets = signed_item.assets
    asset_map = {
        "blue": "blue",
        "green": "green",
        "red": "red",
        "nir": "nir08",
        "swir1": "swir16",
        "swir2": "swir22",
    }

    values: dict[str, np.ndarray] = {}
    for name, asset_key in asset_map.items():
        href = assets[asset_key].href
        with rasterio.open(href) as src:
            values[name] = _scaled(np.array([v[0] for v in src.sample(coordinates)]))

    quality = np.zeros(len(coordinates), dtype=bool)
    qa_asset = assets.get("qa_pixel")
    if qa_asset is not None:
        with rasterio.open(qa_asset.href) as src:
            qa = np.array([v[0] for v in src.sample(coordinates)], dtype="uint16")
        # Landsat QA_PIXEL bits: fill, dilated cloud, cirrus, cloud,
        # cloud shadow, snow/ice.
        mask_bits = (1 << 0) | (1 << 1) | (1 << 2) | (1 << 3) | (1 << 4) | (1 << 5)
        quality = (qa & mask_bits) != 0

    blue = values["blue"]
    green = values["green"]
    red = values["red"]
    nir = values["nir"]
    swir1 = values["swir1"]

    features = pd.DataFrame(values)
    features["ndvi"] = _safe_ratio(nir, red)
    features["ndwi"] = _safe_ratio(green, nir)
    features["mndwi"] = _safe_ratio(green, swir1)
    with np.errstate(divide="ignore", invalid="ignore"):
        features["savi"] = np.where(
            np.abs(nir + red + 0.5) > 1e-9,
            1.5 * (nir - red) / (nir + red + 0.5),
            np.nan,
        )
    features["qa_masked"] = quality
    return features


def _classify_with_rf(
    signed_item,
    point_features: pd.DataFrame,
    bbox: tuple[float, float, float, float],
) -> tuple[np.ndarray, str]:
    # The paper uses labelled training samples for Random Forest.
    # Local labels may not exist, so bootstrap pseudo-labels from MNDWI only
    # as an explicit fallback. This keeps the output schema compatible while
    # avoiding fabricated "ground truth".
    from sklearn.ensemble import RandomForestClassifier

    minx, miny, maxx, maxy = bbox
    grid = []
    for lat in np.linspace(miny + 0.01 * (maxy - miny), maxy - 0.01 * (maxy - miny), 20):
        for lon in np.linspace(minx + 0.01 * (maxx - minx), maxx - 0.01 * (maxx - minx), 20):
            grid.append((float(lon), float(lat)))

    grid_features = _sample_from_signed_assets(signed_item, grid)
    feature_cols = SPECTRAL_COLUMNS + INDEX_COLUMNS
    train = grid_features.dropna(subset=feature_cols).copy()
    if len(train) < 40:
        raise RuntimeError("Insufficient valid live pixels for the classification fallback.")
    labels = (train["mndwi"] >= 0.0).astype(int)
    if labels.nunique() < 2:
        raise RuntimeError("MNDWI fallback produced only one class.")

    clf = RandomForestClassifier(
        n_estimators=150,
        random_state=42,
        class_weight="balanced",
        n_jobs=-1,
    )
    clf.fit(train[feature_cols], labels)
    valid_points = point_features[feature_cols].notna().all(axis=1)
    probability = np.full(len(point_features), np.nan, dtype=float)
    probability[valid_points] = clf.predict_proba(point_features.loc[valid_points, feature_cols])[:, 1]
    return probability, "random_forest_pseudolabel_mndwi"


def run_live() -> dict[str, Any]:
    item_json = search_latest_landsat()
    signed = _sign_item(item_json)
    points = load_segment_points()
    coords = [(p["longitude"], p["latitude"]) for p in points]
    features = _sample_from_signed_assets(signed, coords)

    _, bbox = load_aoi()
    try:
        water_probability, method = _classify_with_rf(signed, features, bbox)
    except Exception:
        # The raw spectral/index output remains valid even if local RF setup
        # cannot be reproduced from available labels.
        mndwi = features["mndwi"].to_numpy(dtype=float)
        water_probability = np.where(
            np.isfinite(mndwi),
            np.clip((mndwi + 1.0) / 2.0, 0.0, 1.0),
            np.nan,
        )
        method = "mndwi_threshold_fallback"

    rows = []
    scene_dt = item_json.get("properties", {}).get("datetime") or item_json.get("properties", {}).get("dtr:start_datetime")
    cloud = item_json.get("properties", {}).get("eo:cloud_cover")

    for i, p in enumerate(points):
        row = {
            **p,
            "observation_date": str(scene_dt)[:10] if scene_dt else dt.date.today().isoformat(),
            "sensor": "Landsat 8/9 C2 L2",
            "source_mode": "real",
            "source": "Microsoft Planetary Computer / Landsat Collection 2 Level-2",
            "scene_id": str(item_json.get("id")),
            "scene_cloud_cover_percent": float(cloud) if cloud is not None else np.nan,
            "classification_method": method,
        }
        for col in SPECTRAL_COLUMNS + INDEX_COLUMNS:
            value = features.iloc[i][col]
            row[col] = float(value) if np.isfinite(value) else np.nan
        prob = water_probability[i]
        row["water_probability"] = float(prob) if np.isfinite(prob) else np.nan
        row["land_water_class"] = (
            "water" if np.isfinite(prob) and prob >= 0.5
            else "land" if np.isfinite(prob)
            else "unknown"
        )
        row["classification_confidence"] = (
            float(max(prob, 1.0 - prob)) if np.isfinite(prob) else np.nan
        )
        row["quality_flag"] = (
            "MASKED" if bool(features.iloc[i]["qa_masked"]) else "GOOD"
        )
        rows.append(row)

    # Save real image preview
    try:
        SATELLITE_RAW_DIR.mkdir(parents=True, exist_ok=True)
        preview_url = item_json.get("assets", {}).get("rendered_preview", {}).get("href")
        if preview_url:
            resp = requests.get(preview_url, timeout=30)
            resp.raise_for_status()
            with open(SATELLITE_RAW_IMG, "wb") as f:
                f.write(resp.content)
            
            raw_meta = {
                "status": "real",
                "scene_id": str(item_json.get("id")),
                "observation_date": str(scene_dt)[:10] if scene_dt else dt.date.today().isoformat(),
                "sensor": "Landsat 8/9 C2 L2",
                "cloud_cover": float(cloud) if cloud is not None else "N/A",
                "source": "Microsoft Planetary Computer",
                "image_url": "/satellite/raw-image"
            }
            with open(SATELLITE_RAW_META, "w", encoding="utf-8") as f:
                json.dump(raw_meta, f, indent=2)
    except Exception as e:
        print(f"Failed to save real preview: {e}")

    return {
        "rows": rows,
        "run": {
            "status": "real",
            "source_mode": "real",
            "provider": "Microsoft Planetary Computer",
            "collection": COLLECTION,
            "paper": PAPER,
            "scene_id": str(item_json.get("id")),
            "scene_datetime": scene_dt,
            "scene_cloud_cover_percent": cloud,
        },
    }


def run_synthetic(reason: str = "live acquisition unavailable") -> dict[str, Any]:
    points = load_segment_points()
    rng = np.random.default_rng(42)
    today = dt.date.today().isoformat()
    rows = []

    for i, p in enumerate(points):
        phase = i / max(1, len(points) - 1)
        mndwi = 0.15 + 0.45 * math.sin(phase * math.pi * 2.0) + rng.normal(0, 0.08)
        ndvi = 0.15 + 0.16 * math.cos(phase * math.pi * 2.5) + rng.normal(0, 0.04)
        ndvi = float(np.clip(ndvi, -0.2, 0.8))
        ndwi = float(mndwi + rng.normal(0, 0.06))
        savi = float(ndvi * 0.85 + rng.normal(0, 0.03))
        blue = float(0.08 + rng.normal(0, 0.015))
        green = float(0.18 + 0.04 * mndwi + rng.normal(0, 0.02))
        red = float(0.12 - 0.02 * ndvi + rng.normal(0, 0.015))
        nir = float(0.24 + 0.10 * ndvi + rng.normal(0, 0.025))
        swir1 = float(0.16 - 0.05 * mndwi + rng.normal(0, 0.02))
        swir2 = float(0.14 - 0.04 * mndwi + rng.normal(0, 0.02))
        prob = float(np.clip((mndwi + 0.7) / 1.4, 0.0, 1.0))

        rows.append(
            {
                **p,
                "observation_date": today,
                "sensor": "Landsat-compatible synthetic",
                "source_mode": "synthetic_fallback",
                "source": "Synthetic fallback",
                "scene_id": "SYNTHETIC_LANDSAT_DEMO",
                "scene_cloud_cover_percent": 0.0,
                "blue": blue,
                "green": green,
                "red": red,
                "nir": nir,
                "swir1": swir1,
                "swir2": swir2,
                "ndvi": ndvi,
                "ndwi": ndwi,
                "mndwi": float(mndwi),
                "savi": savi,
                "water_probability": prob,
                "land_water_class": "water" if prob >= 0.5 else "land",
                "classification_confidence": max(prob, 1.0 - prob),
                "classification_method": "synthetic_mndwi_aligned_demo",
                "quality_flag": "SYNTHETIC",
            }
        )

    # Save synthetic image preview
    try:
        SATELLITE_RAW_DIR.mkdir(parents=True, exist_ok=True)
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(6, 6))
        ax.set_facecolor('#1e293b')
        ax.text(0.5, 0.5, 'SYNTHETIC FALLBACK\nDEMONSTRATION', 
                color='#f59e0b', fontsize=20, ha='center', va='center', weight='bold')
        ax.axis('off')
        fig.savefig(SATELLITE_RAW_IMG, bbox_inches='tight', pad_inches=0.1, facecolor='#1e293b')
        plt.close(fig)
        
        raw_meta = {
            "status": "synthetic_fallback",
            "scene_id": "SYNTHETIC_LANDSAT_DEMO",
            "observation_date": today,
            "sensor": "Synthetic representation",
            "cloud_cover": 0.0,
            "source": "Synthetic satellite-input demonstration",
            "image_url": "/satellite/raw-image"
        }
        with open(SATELLITE_RAW_META, "w", encoding="utf-8") as f:
            json.dump(raw_meta, f, indent=2)
    except Exception as e:
        print(f"Failed to save synthetic preview: {e}")

    return {
        "rows": rows,
        "run": {
            "status": "synthetic",
            "source_mode": "synthetic_fallback",
            "provider": "Synthetic fallback",
            "collection": COLLECTION,
            "paper": PAPER,
            "scene_id": "SYNTHETIC_LANDSAT_DEMO",
            "scene_datetime": today,
            "reason": reason,
        },
    }


def write_outputs(result: dict[str, Any]) -> dict[str, Any]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    df = pd.DataFrame(result["rows"])
    df.to_csv(SATELLITE_CSV, index=False)

    geojson = {"type": "FeatureCollection", "features": []}
    for row in result["rows"]:
        geojson["features"].append(
            {
                "type": "Feature",
                "properties": {
                    "segment_id": row["segment_id"],
                    "observation_date": row["observation_date"],
                    "ndvi": row["ndvi"],
                    "ndwi": row["ndwi"],
                    "mndwi": row["mndwi"],
                    "savi": row["savi"],
                    "water_probability": row["water_probability"],
                    "land_water_class": row["land_water_class"],
                    "classification_confidence": row["classification_confidence"],
                    "quality_flag": row["quality_flag"],
                    "source_mode": row["source_mode"],
                    "scene_id": row["scene_id"],
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [row["longitude"], row["latitude"]],
                },
            }
        )

    SATELLITE_GEOJSON.write_text(json.dumps(geojson, indent=2), encoding="utf-8")

    run_manifest = {
        **result["run"],
        "output_csv": str(SATELLITE_CSV.relative_to(ROOT)),
        "output_geojson": str(SATELLITE_GEOJSON.relative_to(ROOT)),
        "record_count": len(df),
        "columns": list(df.columns),
    }
    SATELLITE_RUN.write_text(json.dumps(run_manifest, indent=2), encoding="utf-8")
    return run_manifest


def main(source: str = "auto") -> dict[str, Any]:
    set_seed = 42
    random.seed(set_seed)
    np.random.seed(set_seed)

    if source in {"auto", "real"}:
        try:
            result = run_live()
        except Exception as exc:
            if source == "real":
                raise
            result = run_synthetic(f"{type(exc).__name__}: {exc}")
    else:
        result = run_synthetic("explicit synthetic mode")

    manifest = write_outputs(result)
    print(json.dumps(manifest, indent=2))
    return manifest


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the paper-aligned satellite domain pipeline.")
    parser.add_argument(
        "--source",
        choices=["auto", "real", "synthetic"],
        default="auto",
        help="auto tries live Landsat first, then synthetic fallback.",
    )
    args = parser.parse_args()
    main(args.source)
